language: generic 
sudo: require
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-us-east-1-138647700966
  bucket_path: "docker-react"
  on:
    branch: master